[project]
name = "toggl-tracker"
version = "0.1.0"
description = "Toggl Command Line Assistant"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.3",
    "simple-term-menu>=1.6.6",
]

[project.scripts]
runme = "toggl-tracker.main2:main"
toggl = "main:main"