target-version = "py313"

exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    "__pycache__",
]

line-length = 100

[lint]
select = ["E", "F", "B", "I"]
ignore = []

[format]
quote-style = "double"

indent-style = "space"
line-ending = "auto"
